services:
    pbx.user_provider:
        class: Pbx\WebBundle\Security\Provider\UserProvider
        public: false
        arguments: ["@fos_user.user_manager"]

    pbx.user_repository:
        class: Pbx\WebBundle\Entity\UserRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: ["PbxWebBundle:User"]

    pbx.form.handler.registration:
        class: Pbx\WebBundle\Form\Handler\RegistrationFormHandler
        parent: fos_user.registration.form.handler.default
        scope: request

    pbx_user.registration.form.type:
        class: Pbx\WebBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: pbx_user_registration }
